# Generated by Django 4.1.5 on 2023-02-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncement',
            name='status',
            field=models.CharField(default='entered', max_length=10),
        ),
    ]
